spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.81.29/mybatis_rabbit_plug?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: ENC(a5rsd8uK8dVi94FUIw0AQdZSId+S8j1v)
rabbit-mybatis-plug:
  banner: true
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    com.plug.test.plugtest.mapper: debug
jasypt:
  encryptor:
    password: NDEyZWQyZTlhZWJhODY2NjRhYTYyYTg3ZTI5NmExYjU=